version: '3.2'

services:
  httpd:
    image: hub.foundries.io/${FACTORY}/shellhttpd:latest
    build: .
    restart: always
    ports:
      - 8080:${PORT-8080}
    environment:
      MSG: "${MSG-Hello world}"