# mosquitto/docker-compose.yml
version: "3"
services:
  mosquitto:
    image: eclipse-mosquitto:1.6.12
    volumes:
      - /var/run/secrets/:/mosquitto/secrets
      - ./run.sh:/run.sh:ro
    command: [/run.sh]
    ports:
      - 1883:1883
    restart: always
