#!/bin/sh

IBM_CONFIG="/config/ibm.config"
while [ ! -f $IBM_CONFIG ]
do
    sleep 5 # or less like 0.2
    echo "Waiting $IBM_CONFIG"
done
    ls -l $IBM_CONFIG
    . $IBM_CONFIG
    echo "WIOTP_IDENTITY_ORGID: $WIOTP_IDENTITY_ORGID"
    echo "WIOTP_IDENTITY_TYPEID: $WIOTP_IDENTITY_TYPEID"
    echo "WIOTP_IDENTITY_DEVICEID: $WIOTP_IDENTITY_DEVICEID"
    echo "WIOTP_AUTH_TOKEN: $WIOTP_AUTH_TOKEN"

export WIOTP_IDENTITY_ORGID=$WIOTP_IDENTITY_ORGID
export WIOTP_IDENTITY_TYPEID=$WIOTP_IDENTITY_TYPEID
export WIOTP_IDENTITY_DEVICEID=$WIOTP_IDENTITY_DEVICEID
export WIOTP_AUTH_TOKEN=$WIOTP_AUTH_TOKEN


python /ibm-iotsdk/service.py
